Run Python file

diff --git a/0-run b/0-run
--- a/0-run
+++ b/0-run
@@ -1,13 +1,7 @@
 #!/bin/bash
 
-if [ -z "$PYFILE" ]; then
-  echo "Error: Environment variable \$PYFILE is not set."
-  exit 1
-fi
-
-if [ ! -f "$PYFILE" ]; then
-  echo "Error: Python file '$PYFILE' not found."
-  exit 1
-fi
+[ -z "$PYFILE" ] && { echo "Error: Environment variable \$PYFILE is not set."; exit 1; }
+[ ! -f "$PYFILE" ] && { echo "Error: Python file '$PYFILE' not found."; exit 1; }
 
 python "$PYFILE"
+
